services:
  uptime-monitor:
    build: .
    container_name: uptime-monitor
    ports:
      - "8000:8000"
    environment:
      CONFIG_PATH: config/targets.yml
      LOG_LEVEL: INFO
      HIGH_LATENCY_MS: "800"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_STATUS_INTERVAL_SECONDS: "1800"
      TELEGRAM_STATUS_TIME: "08:30"
      TELEGRAM_TIMEZONE: "Asia/Jerusalem"
      TELEGRAM_POLL_SECONDS: "3"

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - uptime-monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

